---
version: 2
updates:
  - package-ecosystem: pip
    directory: /.config/
    schedule:
      day: sunday
      interval: weekly
    labels:
      - dependabot-deps-updates
      - skip-changelog
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - docutils
          - pydantic-core
    ignore:
      - dependency-name: docutils  # sphinx-rtd-theme contrins its versions
      - dependency-name: pydantic-core  # pydantic pins specific versions of it
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "skip-changelog"
